//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Locker_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registos
    {
        public int RegistosID { get; set; }
        public Nullable<int> sabadosID { get; set; }
        public Nullable<int> utilizadoresID { get; set; }
    
        public virtual Sabados Sabados { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
