//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Locker_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sabados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sabados()
        {
            this.Registos = new HashSet<Registos>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<bool> Disponibilidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registos> Registos { get; set; }
    }
}
