//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Locker_V2.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Staff
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> igrejaId { get; set; }
    
        public virtual Igreja Igreja { get; set; }
        public SelectList Igrejas { get; set; }
    }
}
