//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Locker_V2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Utilizadores
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Por favor insira o seu Nome!" , AllowEmptyStrings = false)]
        public string Nome { get; set; }
        public string Apelido { get; set; }

        [Required(ErrorMessage = "Por favor insira o seu email!" , AllowEmptyStrings = false)]
        public string Email { get; set; }
        
        [Required(ErrorMessage = "Por favor digite uma password segura!", AllowEmptyStrings = false)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Por favor indique se é membro ou não!", AllowEmptyStrings = false)]
        public Nullable<bool> Membro { get; set; }
    }
}
