//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Locker_V2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Utilizadores
    {
        public int Id { get; set; }

        public string Nome { get; set; }
        public string Apelido { get; set; }

        public string Email { get; set; }
        
        public string Password { get; set; }

        public bool Membro { get; set; }
    }
}
